// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp.Data;

#nullable disable

namespace MyWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125113548_SeedMoreUsers")]
    partial class SeedMoreUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("MyWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$Z3w9zUrZJxzeYSGLTmvQJ.PlT4G249IKXatITBxR0xySgq00W4KC6",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$fYpUMaMcDz82rF7MUwL7KuKuWP6ftx4W5o5YP6Mw9HbEHEhy01.FS",
                            Username = "joya"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$4TJTtxCaIAw7pKlRUmolK..RwqkJeqbiSCD6CevhstfrgVDqOP.Pa",
                            Username = "mary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
